Build an amd64 image with UFS and ZFS, a mac image with UFS and ZFS, and build an i386 image with UFS.

diff --git a/release b/release
--- a/release
+++ b/release
@@ -50,6 +50,27 @@ post_process()
 	sha256_chksum "$1".lzma
 }
 
+rebuild_nomadbsd_components()
+{
+	local arch=$1 fs=$2
+	for c in initbase setupgui installgui reset; do
+		./build -a ${arch} -f ${fs} $c || exit 1
+	done
+}
+
+call_build()
+{
+	if ! ./build $*; then
+		echo "Build command '$*' failed." >&2
+		exit 1
+	fi
+}
+
+create_manifest()
+{
+	pkg -c "${SYSDIR}" info > "$1"
+}
+
 clean()
 {
 	echo "Cleaning ..."
@@ -60,25 +81,35 @@ clean
 
 # Order of arch is important. After building the amd64 image we can
 # use most of it for the mac image.
-for arch in amd64 mac i386; do
-	ARCH=${arch}
-	image=$(imagename)
-	echo "Building ${image} ..."
-	if [ ${arch} = "mac" ]; then
-		# There is no need to rebuild everything for the mac image
-		if ! (./build -a ${arch} initbase && ./build -a ${arch} setupgui && \
-		 ./build -a ${arch} installgui && ./build -a ${arch} image); then
-			echo "Building of ${image} failed." >&2
-			exit 1
+for arch in amd64 mac; do
+	for fs in ufs zfs; do
+		image=$(imagename ${arch} ${fs})
+		echo "Building ${image} ..."
+		if [ ${arch} = "mac" ]; then
+			# There is no need to rebuild everything for the mac image
+			rebuild_nomadbsd_components ${arch} ${fs}
+			call_build -a ${arch} -f ${fs} image
+			if [ ${fs} = "zfs" ]; then
+				create_manifest "${image%${fs}.img}manifest"
+			fi
+		elif [ ${arch} = "amd64" ]; then
+			if [ ${fs} = "zfs" ]; then
+				rebuild_nomadbsd_components ${arch} ${fs}
+				call_build -a ${arch} -f ${fs} image
+				create_manifest "${image%${fs}.img}manifest"
+			else
+				call_build -a ${arch} -f ${fs} all
+			fi
 		fi
-		pkg -c "${SYSDIR}" info > "${image%img}manifest"
-		clean
-	elif ! ./build -a ${arch} all; then
-		echo "Building of ${image} failed." >&2
-		exit 1
-	else
-		pkg -c "${SYSDIR}" info > "${image%img}manifest"
-	fi
-	post_process "${image}"
+		post_process "${image}"
+	done
 done
 
+# In case of i386 just build a UFS image.
+clean
+call_build -a i386 -f UFS all
+image=$(imagename i386 UFS)
+create_manifest "${image%ufs.img}manifest"
+post_process "${image}"
+
+exit 0
